---
title: covid19 R Shiny notebook
output: html_notebook
---

```{r}
# load dependencies
library(rgdal)
library(geojsonio)
library(ggplot2)
library(leaflet)
library(plotly)
library(RColorBrewer)
library(dplyr)
library(broom)
library(mapproj)
library(reshape2)
library(digest)
library(lubridate)
library(spdplyr)
library(rmapshaper)
library(raster)
library(mapview)
library(sf)
library(httr)
library(janitor)
```


```{r}
# try this with: https://www.r-graph-gallery.com/168-load-a-shape-file-into-r.html

zipcode_boundaries <- readOGR("../ZIP_CODE_040114/ZIP_CODE_040114.shp",
  layer = "ZIP_CODE_040114", verbose = FALSE)

# try different table of zipcodes:
alt_zipcode_boundaries <- readOGR("../alt_nyczip/nyc_zip_code_tabulation_areas_polygons.shp",
  layer = "nyc_zip_code_tabulation_areas_polygons", verbose = FALSE)

# fortify the data to obtain dataframe for use by ggplot2
zipcode_boundaries_fortified <- tidy(zipcode_boundaries, region = "ZIPCODE")

# plot it
ggplot() +
  geom_polygon(data = zipcode_boundaries_fortified,
               aes(x = long, y = lat, group = group),
               fill = "#69b3a2", color="white") +
  theme_void()
```

```{r}
# try using info from: https://nceas.github.io/oss-lessons/spatial-data-gis-law/3-mon-intro-gis-in-r.html

class(zipcode_boundaries)

extent(zipcode_boundaries)

plot(zipcode_boundaries, main = "NYC zipcode boundaries")
```


```{r}
# convert spatial data frame to geojson
# nyc_json <- geojson_json(zipcode_boundaries)
# save to local file
# geojson_write(nyc_json, file = "./nyc.geojson")

alt_nyc_json <- geojson_json(alt_zipcode_boundaries)
geojson_write(alt_nyc_json, file = "./alt_nyc.geojson")
```

```{r}
# create leaflet object
pal <- colorNumeric("viridis", NULL)

leaflet(alt_zipcode_boundaries) %>%
#  addProviderTiles(providers$OpenStreetMap) %>% 
  addTiles() %>% #add basemap
#  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
#    fillColor = ~pal(borough),
#    label = borough) %>%
  addPolylines(color = "#444444", 
               weight = 1, 
               smoothFactor = 0.5, 
               opacity = 1.0)
```


```{r}
### run it all again but this time with SF (faster?)

zipcode_sf <- st_read("alt_nyczip/nyc_zip_code_tabulation_areas_polygons.shp")
altzip_sf <- st_read("../ZIP_CODE_040114/ZIP_CODE_040114.shp")

ggplot() +
  geom_sf(data=zipcode_sf, aes(fill = borough)) 
```

```{r}
# mapview function
# mapview(zipcode_sf)
mapview(altzip_sf)
```

```{r}
# try leaflet with this
pal <- colorFactor(rainbow(5), zipcode_sf$borough)

leaflet(zipcode_sf) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%  #add simpler basemap 
  addPolygons(stroke = FALSE, 
              smoothFactor = 0.3, 
              fillOpacity = 0.2,
    highlight = highlightOptions(color = "white", weight = 10, bringToFront = TRUE))  %>%
  addPolylines(color = "#444444", 
               weight = 1, 
               smoothFactor = 0.5, 
               opacity = 1.0, 
               highlightOptions = highlightOptions(color = "white", 
                                                   weight = 5, 
                                                   bringToFront = F, 
                                                   opacity = 1))
```


```{r}
r <- httr::GET('http://data.beta.nyc//dataset/0ff93d2d-90ba-457c-9f7e-39e47bf2ac5f/resource/35dd04fb-81b3-479b-a074-a27a37888ce7/download/d085e2f8d0b54d4590b1e7d1f35594c1pediacitiesnycneighborhoods.geojson')
nyc_neighborhoods <- readOGR(content(r,'text'), 'OGRGeoJSON', verbose = F)
summary(nyc_neighborhoods)


```

```{r}
leaflet(nyc_neighborhoods) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%  #add simpler basemap 
  addPolygons(popup = ~neighborhood)
```




```{r}
### combine zipcode geometric data with cleaned dataframe
altzip_sf <- st_read("cleaned_data/ZIP_CODE_040114.shp")
cleaned_sf <- geojsonsf::geojson_sf("cleaned_data/combined_covid_data.geojson")

colnames(zipcode_sf)[which(names(zipcode_sf) == "postalcode")] <- "ZIPCODE"

# make certain of zipcode overlap between the two dataframes
setdiff(cleaned_sf$ZIPCODE, altzip_sf$ZIPCODE)

# altzip only need ZIPCODE and geometry columns:
altzip_sf_compact <- subset(altzip_sf, select = c('ZIPCODE', 'geometry'))

```


```{r}
# 
cleaned_sf_compact <- within(cleaned_sf, rm('geometry'))
cleaned_sf_compact <- cleaned_sf_compact %>% st_set_geometry(NULL)
class(cleaned_sf_compact)
#combined_sf <- merge(cleaned_sf, altzip_sf_compact, by = 'ZIPCODE')
```

```{r}
combined_sf <- merge(altzip_sf_compact, cleaned_sf_compact, by = 'ZIPCODE')

class(combined_sf)

mapview(combined_sf)
```

```{r}
# let's try leaflet with this new combined_sf:

pal <- colorFactor(rainbow(5), combined_sf$PO_NAME)

leaflet(combined_sf) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%  #add simpler basemap 
  addPolygons(stroke = TRUE, 
              smoothFactor = 0.3, 
              fillOpacity = 0.2,
    highlight = highlightOptions(color = "white", weight = 10, bringToFront = TRUE))
#  addPolylines(color = "#444444", 
#               weight = 1, 
#               smoothFactor = 0.5, 
#               opacity = 1.0, 
#               highlightOptions = highlightOptions(color = "white", 
#                                                   weight = 5, 
#                                                   bringToFront = F, 
#                                                   opacity = 1))
```

```{r}
# how is the massachusetts dataframe organised?
ma_spdf = geojson_read("cleaned_data/cb_2018_ma_county_5m.json",  what = "sp")

ma_spdf
```

```{r}
# how is the nyc zipcode dataframe organised?
ny_spdf = geojson_read("cleaned_data/nyc-zip-code-tabulation-areas-polygons.geojson",  what = "sp")
#ny_spdf <- readOGR("cleaned_data/ZIP_CODE_040114.shp", layer = "ZIP_CODE_040114", verbose = #FALSE)
ny_spdf
```

```{r}

pal <- colorFactor(rainbow(5), ny_spdf$borough) 

leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%  #add simpler basemap 
  addPolygons(data = ny_spdf,
              weight = 1,
              stroke = TRUE, 
              smoothFactor = 0.3, 
              fillOpacity = 0.2,
              fillColor = ~pal(ny_spdf$borough),
    highlight = highlightOptions(color = "white", weight = 1, bringToFront = TRUE))
```


```{r}
# incorporate dataframe, merge by zipcode
df_leaflet = ny_spdf
df_final = read.csv("cleaned_data/zip_count_rate_temp.csv", check.names = F, stringsAsFactors = F)

df_final <- clean_names(df_final)

ny_spdf@data
```

```{r}
# rename ZIP column to postalCode to enable merge
colnames(df_final)[which(names(df_final) == "zip")] <- "postalCode"

df_final$postalCode <- as.character(df_final$postalCode)

# recode DATE column as date data type
df_final$date <- as.Date(df_final$date, "%Y-%m-%d")

df_leaflet@data = left_join(df_leaflet@data, df_final,by = "postalCode")

```

```{r}
# subset by date
#target_date <- subset(df_final, DATE == as.Date("2020-04-21") )
target_date <-  as.Date("2020-04-21")
target_date_pos <- subset(df_leaflet@data, date==target_date, select=c('postalCode','positive'))

mybins = seq(0, plyr::round_any(max(target_date_pos$positive), 1000, f=ceiling), by = 500)
mypalette = colorBin( palette="YlOrRd", domain = target_date_pos$positive, na.color="transparent", bins=mybins)

mytag = paste(
  "Zipcode: ", df_leaflet@data$postalCode,"<br/>", 
  "Borough: ", df_leaflet@data$name,"<br/>",
  "Positive cases: ",target_date_pos$positive, "<br/>",
  sep="") %>%
  lapply(htmltools::HTML)

```

```{r}
leaflet(df_leaflet) %>% 
  addProviderTiles(providers$CartoDB.Positron) %>%  #add simpler basemap
#  clearShapes() %>%
  addPolygons(data =df_leaflet, 
              fillColor = ~mypalette(target_date_pos$positive),
              fillOpacity = 0.5,
              stroke=TRUE,
              weight=0.8,
              color="#000000",
              label = mytag,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "10px",
                direction = "auto"),
              highlight = highlightOptions(color = "white", weight = 2, bringToFront = TRUE)) %>%
  clearControls() %>%
  addLegend( pal=mypalette, values=target_date_pos$positive, opacity=0.5, title = "Cases", position = "bottomleft" )
```

```{r}
# data clean-up
df1 = read.csv("cleaned_data/zip_count_rate_temp.csv", check.names = F, stringsAsFactors = F)

df1 <- clean_names(df1)

df_sub <- subset(df1, select = c('population', 'zip', 'positive', 'total', 'name', 'population_count', 'male_count', 'female_count', 'white_count', 'black_count', 'native_american_count', 'asian_count', 'hawaiian_pacific_islander_count', 'other_count', 'two_or_more_race_count', 'hispanic_race_count', 'median_household_income', 'latitude', 'longitude', 'date'))


```

```{r}
# compute some basic statistics that we need like proportions, population_weighted stats per zipcode

df_to_csv <- df_sub %>%
  as_tibble() %>%
  mutate(
    positive_per_capita = round(1000000 * positive / population, 0),
    tests_per_capita = round(1000000 * total / population, 0),
    male_prop = round(100 * male_count / (male_count + female_count),1),
    female_prop = round(100*female_count / (male_count + female_count), 1),
    white_prop = round(100*white_count / (male_count + female_count), 1),
    black_prop = round(100*black_count / (male_count + female_count),1),
    asian_prop = round(100*asian_count / (male_count + female_count),1),
    hawaiian_pi_prop = round(100*hawaiian_pacific_islander_count / (male_count + female_count),1),
    other_prop = round(100*other_count / (male_count + female_count),1),
    multi_race_prop = round(100*two_or_more_race_count / (male_count + female_count),1),
    hispanic_prop = round(100*hispanic_race_count / (male_count + female_count),1)
  )

```



```{r}
# write data to clean csv
write.csv(df_to_csv, "cleaned_data/non_polygon_df_final.csv", row.names = F)
```

```{r}
df_final = read.csv("cleaned_data/non_polygon_df_final.csv", check.names = F, stringsAsFactors = F)
```

```{r}
max(df_final$positive_per_capita, na.rm=T)
```

